# Required:
# dein toml

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add='''
 nnoremap <silent> <space>fr :<C-u>Denite file_mru<CR>
 nnoremap <silent> <space>fb :<C-u>Denite buffer<CR>
 nnoremap <silent> <space>fy :<C-u>Denite neoyank<CR>
 nnoremap <silent> <space>ff :<C-u>Denite file_rec<CR>
 nnoremap <silent> <space>fu :<C-u>Denite outline<CR>
'''

[[plugins]]
repo = 'lifepillar/vim-solarized8'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-theme']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

